http://localhost:3001/api/v1/meals 
###


POST http://localhost:3001/api/v1/meals/sample HTTP/1.1
content-type: application/json

{ "name": "Spicy Arrabiata Penne",
    "category": "Vegetarian",
    "instructions": "Bring a large pot of water to a boil...",
    "ingredients": ["Penne", "Tomato Sauce", "Garlic"]}

###

Get http://localhost:3001/api/v1/meals/random.php HTTP/1.1
content-type: application/json

###



