@endpoint = http://localhost:3001/api/v1/meals
POST {{endpoint}}/sample HTTP/1.1
content-type: application/json

{ "name": "Pizza",
    "category": "Vegetarian",
    "instructions": "Bring a large pot of water to a boil...",
    "ingredients": ["Penne", "Tomato Sauce", "Garlic"]}

###

GET {{endpoint}}/search/pizza HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/674cd7d1d9e1adf98f72689a HTTP/1.1
content-type: application/json

###
GET {{endpoint}}/letter/a HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/random HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/categories HTTP/1.1
content-type: application/json

###
